name: field_login
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  # 图片缓存
  cached_network_image: ^3.3.1
  # WebView
  flutter_inappwebview: ^6.0.0
  socket_io_client: ^3.1.2
  web_socket_channel: ^3.0.3
  easy_refresh: ^3.3.2
  # 本地存储
  shared_preferences: ^2.2.2
  # 网络请求
  dio: ^5.7.0                         
  system_info2: ^2.0.0
  device_info_plus: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/icons/
      - assets/webview/test_page.html